package com.umutcansahin.recyclerviewinrecyclerview

object CompanyList {
    val list = listOf<Company>(
        Company(
            "Apple",
            3,
            listOf(
                "umut",
                "ali",
                "mehmet",
                "umut",
                "ali",
                "mehmet",
                "kadir",
                "emre",
                "mehmet",
                "hasan",
                "hakan",
                "emel"
            )
        ),
        Company(
            "Tesla",
            6,
            listOf(
                "kadir",
                "emre",
                "mehmet",
                "hasan",
                "hakan",
                "emel",
                "kadir",
                "emre",
                "mehmet",
                "hasan",
                "hakan",
                "emel"
            )
        ),
        Company(
            "Starbucks",
            5,
            listOf(
                "ayse",
                "ibo",
                "mehmet",
                "elif",
                "gurkan",
                "ayse",
                "ibo",
                "mehmet",
                "elif",
                "gurkan",
            )
        ),
        Company(
            "Microsoft",
            1,
            listOf(
                "bill",
                "bill",
                "bill",
                "bill",
                "bill",
                "bill",
                "bill",
                "bill",
                "bill",
                "bill",
                "bill",
                "bill",
            )
        ),
        Company(
            "THY",
            4,
            listOf(
                "akif",
                "ali",
                "mehmet",
                "merve",
                "pelin",
                "akif",
                "ali",
                "mehmet",
                "merve",
                "pelin",
            )
        ),
        Company(
            "Getir",
            7,
            workerName = listOf(
                "sude",
                "buse",
                "gözde",
                "ömer",
                "furkan",
                "cengiz",
                "umut",
                "sude",
                "buse",
                "gözde",
                "ömer",
                "furkan",
                "cengiz",
                "umut"
            )
        ),
        Company(
            "Apple",
            3,
            listOf(
                "umut",
                "ali",
                "mehmet",
                "umut",
                "ali",
                "mehmet",
                "umut",
                "ali",
                "mehmet",
                "umut",
                "ali",
                "mehmet",
                "umut",
                "ali",
                "mehmet",
            )
        ),
        Company(
            "Tesla",
            6,
            listOf(
                "kadir",
                "emre",
                "mehmet",
                "hasan",
                "hakan",
                "emel",
                "kadir",
                "emre",
                "mehmet",
                "hasan",
                "hakan",
                "emel"
            )
        ),
        Company(
            "Starbucks",
            5,
            listOf(
                "ayse",
                "ibo",
                "mehmet",
                "elif",
                "gurkan",
                "ayse",
                "ibo",
                "mehmet",
                "elif",
                "gurkan"
            )
        ),
        Company(
            "Microsoft",
            1,
            listOf("bill")
        ),
        Company(
            "THY",
            4,
            listOf(
                "akif",
                "ali",
                "mehmet",
                "merve",
                "pelin",
                "akif",
                "ali",
                "mehmet",
                "merve",
                "pelin"
            )
        ),
        Company(
            "Getir",
            7,
            listOf(
                "sude",
                "buse",
                "gözde",
                "ömer",
                "furkan",
                "cengiz",
                "umut",
                "sude",
                "buse",
                "gözde",
                "ömer",
                "furkan",
                "cengiz",
                "umut"
            )
        ),
    )
}